server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: movieapp-api

  datasource:
    url: jdbc:postgresql://mydbinstance.cluguxq5aeux.us-east-1.rds.amazonaws.com:5432/moviedatabase
    username: upgrad123
    password: Ashu123#

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
